include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    uri_has_not_been_generated: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "bricks/**"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    public_member_api_docs: false
