plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

fun loadProperties(fileName: String): Map<String, String> {
    val props = hashMapOf<String, String>()
    val file = rootProject.file("../$fileName")
    if (file.exists()) {
        file.readLines().forEach { line ->
            val trimmed = line.trim()
            if (trimmed.isNotEmpty() && !trimmed.startsWith("#") && trimmed.contains("=")) {
                val (key, value) = trimmed.split("=", limit = 2)
                props[key.trim()] = value.trim()
            }
        }
    }
    return props
}

val debugKeyProperties = loadProperties("debug-key.properties")
val releaseKeyProperties = loadProperties("key.properties")

android {
    namespace = "org.benaiah.app"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    signingConfigs {
        getByName("debug") {
            storeFile = rootProject.file("../${debugKeyProperties["storeFile"] ?: "debug.keystore"}")
            storePassword = debugKeyProperties["storePassword"]
            keyAlias = debugKeyProperties["keyAlias"]
            keyPassword = debugKeyProperties["keyPassword"]
        }
        create("release") {
            val storeFilePath = releaseKeyProperties["storeFile"]
            if (storeFilePath != null) {
                storeFile = rootProject.file("../$storeFilePath")
                storePassword = releaseKeyProperties["storePassword"]
                keyAlias = releaseKeyProperties["keyAlias"]
                keyPassword = releaseKeyProperties["keyPassword"]
            } else {
                // Fallback to debug if release keys are missing
                storeFile = rootProject.file("../${debugKeyProperties["storeFile"] ?: "debug.keystore"}")
                storePassword = debugKeyProperties["storePassword"]
                keyAlias = debugKeyProperties["keyAlias"]
                keyPassword = debugKeyProperties["keyPassword"]
            }
        }
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "org.benaiah.app"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("release")
        }
    }
}

flutter {
    source = "../.."
}

// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----
